// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: campaign/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the campaign module's genesis state.
type GenesisState struct {
	Campaigns       []Campaign       `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns"`
	CampaignCounter uint64           `protobuf:"varint,2,opt,name=campaignCounter,proto3" json:"campaignCounter,omitempty"`
	CampaignChains  []CampaignChains `protobuf:"bytes,3,rep,name=campaignChains,proto3" json:"campaignChains"`
	MainnetAccounts []MainnetAccount `protobuf:"bytes,4,rep,name=mainnetAccounts,proto3" json:"mainnetAccounts"`
	TotalShares     uint64           `protobuf:"varint,5,opt,name=totalShares,proto3" json:"totalShares,omitempty"`
	Params          Params           `protobuf:"bytes,6,opt,name=params,proto3" json:"params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_34fad1c9ee281f6a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetCampaigns() []Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

func (m *GenesisState) GetCampaignCounter() uint64 {
	if m != nil {
		return m.CampaignCounter
	}
	return 0
}

func (m *GenesisState) GetCampaignChains() []CampaignChains {
	if m != nil {
		return m.CampaignChains
	}
	return nil
}

func (m *GenesisState) GetMainnetAccounts() []MainnetAccount {
	if m != nil {
		return m.MainnetAccounts
	}
	return nil
}

func (m *GenesisState) GetTotalShares() uint64 {
	if m != nil {
		return m.TotalShares
	}
	return 0
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "tendermint.spn.campaign.GenesisState")
}

func init() { proto.RegisterFile("campaign/genesis.proto", fileDescriptor_34fad1c9ee281f6a) }

var fileDescriptor_34fad1c9ee281f6a = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcf, 0x4f, 0xc2, 0x30,
	0x18, 0xdd, 0x04, 0x49, 0x2c, 0x46, 0x92, 0x46, 0x65, 0xe1, 0x50, 0xa6, 0x17, 0x77, 0xea, 0x12,
	0x3c, 0x7b, 0x10, 0x62, 0xf4, 0x62, 0x62, 0x20, 0xc6, 0xc4, 0x0b, 0x29, 0xb3, 0xd9, 0x1a, 0x59,
	0xdb, 0xac, 0xc5, 0x1f, 0xff, 0x05, 0x7f, 0x16, 0x47, 0x8e, 0x9e, 0x8c, 0x81, 0x7f, 0xc4, 0xb0,
	0x75, 0x43, 0x47, 0x08, 0xb7, 0xaf, 0xef, 0x7b, 0xdf, 0x7b, 0xfd, 0x5e, 0x0b, 0x4e, 0x03, 0x12,
	0x4b, 0xc2, 0x42, 0xee, 0x87, 0x94, 0x53, 0xc5, 0x14, 0x96, 0x89, 0xd0, 0x02, 0x36, 0x35, 0xe5,
	0x2f, 0x34, 0x89, 0x19, 0xd7, 0x58, 0x49, 0x8e, 0x73, 0x5a, 0xeb, 0x38, 0x14, 0xa1, 0x48, 0x39,
	0xfe, 0xaa, 0xca, 0xe8, 0x2d, 0x54, 0xc8, 0xe4, 0xc5, 0x30, 0x88, 0x08, 0xe3, 0x46, 0xae, 0xb5,
	0xb6, 0x79, 0xa3, 0x4a, 0x33, 0x1e, 0x1a, 0xbc, 0xb9, 0x31, 0xb7, 0x21, 0x18, 0x13, 0xc6, 0x39,
	0xd5, 0x43, 0x12, 0x04, 0x62, 0xc2, 0xb5, 0xe9, 0x9f, 0x14, 0x7d, 0x49, 0x12, 0x12, 0x1b, 0x9f,
	0xf3, 0x69, 0x05, 0x1c, 0xde, 0x66, 0x8b, 0x0c, 0x34, 0xd1, 0x14, 0xde, 0x80, 0x83, 0x9c, 0xa9,
	0x1c, 0xdb, 0xad, 0x78, 0xf5, 0xce, 0x19, 0xde, 0xb2, 0x1b, 0xee, 0x99, 0xa2, 0x5b, 0x9d, 0x7d,
	0xb7, 0xad, 0xfe, 0x7a, 0x12, 0x7a, 0xa0, 0x91, 0x1f, 0x7a, 0xab, 0x5b, 0xd0, 0xc4, 0xd9, 0x73,
	0x6d, 0xaf, 0xda, 0x2f, 0xc3, 0xf0, 0x11, 0x1c, 0x15, 0x50, 0x9a, 0x80, 0x53, 0x49, 0x5d, 0x2f,
	0x76, 0xba, 0x66, 0x74, 0xe3, 0x5d, 0x12, 0x81, 0x4f, 0xa0, 0x61, 0x82, 0xb8, 0xce, 0x72, 0x50,
	0x4e, 0x75, 0x87, 0xee, 0xfd, 0x3f, 0xbe, 0xd1, 0x2d, 0xab, 0x40, 0x17, 0xd4, 0xb5, 0xd0, 0x64,
	0x3c, 0x88, 0x48, 0x42, 0x95, 0xb3, 0x9f, 0x6e, 0xf5, 0x17, 0x82, 0x57, 0xa0, 0x96, 0x65, 0xec,
	0xd4, 0x5c, 0xdb, 0xab, 0x77, 0xda, 0x5b, 0x1d, 0x1f, 0x52, 0x9a, 0x71, 0x32, 0x43, 0xdd, 0xbb,
	0xd9, 0x02, 0xd9, 0xf3, 0x05, 0xb2, 0x7f, 0x16, 0xc8, 0x9e, 0x2e, 0x91, 0x35, 0x5f, 0x22, 0xeb,
	0x6b, 0x89, 0xac, 0x67, 0x1c, 0x32, 0x1d, 0x4d, 0x46, 0x38, 0x10, 0xb1, 0xaf, 0x24, 0x1d, 0x8f,
	0x55, 0x44, 0x24, 0xf5, 0x39, 0xd5, 0xef, 0x22, 0x79, 0xf5, 0x3f, 0x8a, 0x3f, 0xe1, 0xeb, 0x4f,
	0x49, 0xd5, 0xa8, 0x96, 0xbe, 0xf1, 0xe5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xbc, 0x81,
	0x30, 0xb4, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.TotalShares != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TotalShares))
		i--
		dAtA[i] = 0x28
	}
	if len(m.MainnetAccounts) > 0 {
		for iNdEx := len(m.MainnetAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MainnetAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.CampaignChains) > 0 {
		for iNdEx := len(m.CampaignChains) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CampaignChains[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.CampaignCounter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CampaignCounter))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Campaigns) > 0 {
		for iNdEx := len(m.Campaigns) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Campaigns[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Campaigns) > 0 {
		for _, e := range m.Campaigns {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CampaignCounter != 0 {
		n += 1 + sovGenesis(uint64(m.CampaignCounter))
	}
	if len(m.CampaignChains) > 0 {
		for _, e := range m.CampaignChains {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.MainnetAccounts) > 0 {
		for _, e := range m.MainnetAccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TotalShares != 0 {
		n += 1 + sovGenesis(uint64(m.TotalShares))
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Campaigns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Campaigns = append(m.Campaigns, Campaign{})
			if err := m.Campaigns[len(m.Campaigns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignCounter", wireType)
			}
			m.CampaignCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignChains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CampaignChains = append(m.CampaignChains, CampaignChains{})
			if err := m.CampaignChains[len(m.CampaignChains)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainnetAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MainnetAccounts = append(m.MainnetAccounts, MainnetAccount{})
			if err := m.MainnetAccounts[len(m.MainnetAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			m.TotalShares = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalShares |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
