// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: campaign/mainnet_account.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MainnetAccount struct {
	CampaignID uint64 `protobuf:"varint,1,opt,name=campaignID,proto3" json:"campaignID,omitempty"`
	Address    string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Shares     Shares `protobuf:"bytes,3,rep,name=shares,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin,castrepeated=Shares" json:"shares"`
}

func (m *MainnetAccount) Reset()         { *m = MainnetAccount{} }
func (m *MainnetAccount) String() string { return proto.CompactTextString(m) }
func (*MainnetAccount) ProtoMessage()    {}
func (*MainnetAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a87a85fe8b4c45d, []int{0}
}
func (m *MainnetAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MainnetAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MainnetAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MainnetAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainnetAccount.Merge(m, src)
}
func (m *MainnetAccount) XXX_Size() int {
	return m.Size()
}
func (m *MainnetAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MainnetAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MainnetAccount proto.InternalMessageInfo

func (m *MainnetAccount) GetCampaignID() uint64 {
	if m != nil {
		return m.CampaignID
	}
	return 0
}

func (m *MainnetAccount) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MainnetAccount) GetShares() Shares {
	if m != nil {
		return m.Shares
	}
	return nil
}

type MainnetAccountBalance struct {
	CampaignID uint64                                   `protobuf:"varint,1,opt,name=campaignID,proto3" json:"campaignID,omitempty"`
	Address    string                                   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Coins      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=coins,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins"`
}

func (m *MainnetAccountBalance) Reset()         { *m = MainnetAccountBalance{} }
func (m *MainnetAccountBalance) String() string { return proto.CompactTextString(m) }
func (*MainnetAccountBalance) ProtoMessage()    {}
func (*MainnetAccountBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a87a85fe8b4c45d, []int{1}
}
func (m *MainnetAccountBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MainnetAccountBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MainnetAccountBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MainnetAccountBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MainnetAccountBalance.Merge(m, src)
}
func (m *MainnetAccountBalance) XXX_Size() int {
	return m.Size()
}
func (m *MainnetAccountBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_MainnetAccountBalance.DiscardUnknown(m)
}

var xxx_messageInfo_MainnetAccountBalance proto.InternalMessageInfo

func (m *MainnetAccountBalance) GetCampaignID() uint64 {
	if m != nil {
		return m.CampaignID
	}
	return 0
}

func (m *MainnetAccountBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MainnetAccountBalance) GetCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Coins
	}
	return nil
}

func init() {
	proto.RegisterType((*MainnetAccount)(nil), "tendermint.spn.campaign.MainnetAccount")
	proto.RegisterType((*MainnetAccountBalance)(nil), "tendermint.spn.campaign.MainnetAccountBalance")
}

func init() { proto.RegisterFile("campaign/mainnet_account.proto", fileDescriptor_0a87a85fe8b4c45d) }

var fileDescriptor_0a87a85fe8b4c45d = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xbd, 0x6e, 0xea, 0x30,
	0x18, 0x8d, 0x2f, 0xf7, 0x72, 0x75, 0x7d, 0xa5, 0x0e, 0x11, 0x55, 0x03, 0x83, 0x41, 0x2c, 0xcd,
	0x82, 0x2d, 0xe8, 0xd4, 0x91, 0xb4, 0x43, 0x3b, 0x74, 0x09, 0x5b, 0x3b, 0x20, 0x27, 0xb1, 0x42,
	0x44, 0x62, 0x47, 0xb1, 0xe9, 0xcf, 0x3b, 0x74, 0xe8, 0x73, 0x74, 0xee, 0x43, 0x30, 0x22, 0xa6,
	0x4e, 0xb4, 0x82, 0xb7, 0x60, 0xaa, 0x88, 0x4d, 0x45, 0x37, 0x3a, 0x74, 0xf2, 0xcf, 0x39, 0xdf,
	0xf9, 0xce, 0xf9, 0xf4, 0x41, 0x14, 0xd2, 0x2c, 0xa7, 0x49, 0xcc, 0x49, 0x46, 0x13, 0xce, 0x99,
	0x1a, 0xd2, 0x30, 0x14, 0x13, 0xae, 0x70, 0x5e, 0x08, 0x25, 0xec, 0x23, 0xc5, 0x78, 0xc4, 0x8a,
	0x2c, 0xe1, 0x0a, 0xcb, 0x9c, 0xe3, 0x2d, 0xbd, 0x51, 0x8b, 0x45, 0x2c, 0x4a, 0x0e, 0xd9, 0xdc,
	0x34, 0xbd, 0x81, 0x42, 0x21, 0x33, 0x21, 0x49, 0x40, 0x25, 0x23, 0xb7, 0xdd, 0x80, 0x29, 0xda,
	0x25, 0xa1, 0x48, 0xb8, 0xc1, 0xeb, 0x1a, 0x1f, 0xea, 0x42, 0xfd, 0xd0, 0x50, 0x7b, 0x0e, 0xe0,
	0xc1, 0x95, 0xf6, 0xd0, 0xd7, 0x16, 0x6c, 0x04, 0xe1, 0xb6, 0xdf, 0xe5, 0xb9, 0x03, 0x5a, 0xc0,
	0xfd, 0xed, 0xef, 0xfc, 0xd8, 0x3d, 0xf8, 0x97, 0x46, 0x51, 0xc1, 0xa4, 0x74, 0x7e, 0xb5, 0x80,
	0xfb, 0xcf, 0x73, 0xe6, 0x2f, 0x9d, 0x9a, 0x51, 0xed, 0x6b, 0x64, 0xa0, 0x8a, 0x84, 0xc7, 0xfe,
	0x96, 0x68, 0xa7, 0xb0, 0x2a, 0x47, 0xb4, 0x60, 0xd2, 0xa9, 0xb4, 0x2a, 0xee, 0xff, 0x5e, 0x1d,
	0x1b, 0xfe, 0xc6, 0x32, 0x36, 0x96, 0xf1, 0x99, 0x48, 0xb8, 0x77, 0x3a, 0x5d, 0x34, 0xad, 0xf5,
	0xa2, 0x79, 0x1c, 0x27, 0x6a, 0x34, 0x09, 0x70, 0x28, 0x32, 0x63, 0xd9, 0x1c, 0x1d, 0x19, 0x8d,
	0x89, 0x7a, 0xc8, 0x99, 0x2c, 0x0b, 0x9e, 0xdf, 0x9a, 0xd5, 0x41, 0xa9, 0xed, 0x9b, 0x1e, 0xed,
	0x35, 0x80, 0x87, 0x5f, 0x43, 0x79, 0x34, 0xa5, 0x3c, 0x64, 0x3f, 0x92, 0xed, 0x11, 0xc0, 0x3f,
	0x9b, 0x61, 0xef, 0x91, 0xed, 0xe6, 0xfb, 0xd9, 0xdc, 0x3d, 0xa9, 0xd2, 0xd7, 0x26, 0xbc, 0x8b,
	0xe9, 0x12, 0x81, 0xd9, 0x12, 0x81, 0xf7, 0x25, 0x02, 0x4f, 0x2b, 0x64, 0xcd, 0x56, 0xc8, 0x7a,
	0x5d, 0x21, 0xeb, 0x1a, 0xef, 0x48, 0xc9, 0x9c, 0xa5, 0xa9, 0x1c, 0xd1, 0x9c, 0x11, 0xce, 0xd4,
	0x9d, 0x28, 0xc6, 0xe4, 0x9e, 0x7c, 0x6e, 0x65, 0x29, 0x1b, 0x54, 0xcb, 0x15, 0x39, 0xf9, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x57, 0x71, 0xfd, 0x8a, 0xae, 0x02, 0x00, 0x00,
}

func (m *MainnetAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MainnetAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MainnetAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Shares) > 0 {
		for iNdEx := len(m.Shares) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Shares[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMainnetAccount(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMainnetAccount(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.CampaignID != 0 {
		i = encodeVarintMainnetAccount(dAtA, i, uint64(m.CampaignID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MainnetAccountBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MainnetAccountBalance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MainnetAccountBalance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMainnetAccount(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMainnetAccount(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.CampaignID != 0 {
		i = encodeVarintMainnetAccount(dAtA, i, uint64(m.CampaignID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMainnetAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovMainnetAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MainnetAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CampaignID != 0 {
		n += 1 + sovMainnetAccount(uint64(m.CampaignID))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMainnetAccount(uint64(l))
	}
	if len(m.Shares) > 0 {
		for _, e := range m.Shares {
			l = e.Size()
			n += 1 + l + sovMainnetAccount(uint64(l))
		}
	}
	return n
}

func (m *MainnetAccountBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CampaignID != 0 {
		n += 1 + sovMainnetAccount(uint64(m.CampaignID))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMainnetAccount(uint64(l))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovMainnetAccount(uint64(l))
		}
	}
	return n
}

func sovMainnetAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMainnetAccount(x uint64) (n int) {
	return sovMainnetAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MainnetAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMainnetAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MainnetAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MainnetAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignID", wireType)
			}
			m.CampaignID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMainnetAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMainnetAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMainnetAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Shares = append(m.Shares, github_com_cosmos_cosmos_sdk_types.Coin{})
			if err := m.Shares[len(m.Shares)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMainnetAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MainnetAccountBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMainnetAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MainnetAccountBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MainnetAccountBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignID", wireType)
			}
			m.CampaignID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMainnetAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CampaignID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMainnetAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMainnetAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, github_com_cosmos_cosmos_sdk_types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMainnetAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMainnetAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMainnetAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMainnetAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMainnetAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMainnetAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMainnetAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMainnetAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMainnetAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMainnetAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMainnetAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMainnetAccount = fmt.Errorf("proto: unexpected end of group")
)
