// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reward/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetRewards struct {
	Provider         string                                   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	LaunchID         uint64                                   `protobuf:"varint,2,opt,name=launchID,proto3" json:"launchID,omitempty"`
	Coins            github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=coins,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins"`
	LastRewardHeight int64                                    `protobuf:"varint,4,opt,name=lastRewardHeight,proto3" json:"lastRewardHeight,omitempty"`
}

func (m *MsgSetRewards) Reset()         { *m = MsgSetRewards{} }
func (m *MsgSetRewards) String() string { return proto.CompactTextString(m) }
func (*MsgSetRewards) ProtoMessage()    {}
func (*MsgSetRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_837cc604acddc9f4, []int{0}
}
func (m *MsgSetRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetRewards.Merge(m, src)
}
func (m *MsgSetRewards) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetRewards.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetRewards proto.InternalMessageInfo

func (m *MsgSetRewards) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *MsgSetRewards) GetLaunchID() uint64 {
	if m != nil {
		return m.LaunchID
	}
	return 0
}

func (m *MsgSetRewards) GetCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Coins
	}
	return nil
}

func (m *MsgSetRewards) GetLastRewardHeight() int64 {
	if m != nil {
		return m.LastRewardHeight
	}
	return 0
}

type MsgSetRewardsResponse struct {
	PreviousCoins            github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=previousCoins,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"previousCoins"`
	PreviousLastRewardHeight int64                                    `protobuf:"varint,2,opt,name=previousLastRewardHeight,proto3" json:"previousLastRewardHeight,omitempty"`
	NewCoins                 github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=newCoins,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"newCoins"`
	NewLastRewardHeight      int64                                    `protobuf:"varint,4,opt,name=newLastRewardHeight,proto3" json:"newLastRewardHeight,omitempty"`
}

func (m *MsgSetRewardsResponse) Reset()         { *m = MsgSetRewardsResponse{} }
func (m *MsgSetRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetRewardsResponse) ProtoMessage()    {}
func (*MsgSetRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_837cc604acddc9f4, []int{1}
}
func (m *MsgSetRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetRewardsResponse.Merge(m, src)
}
func (m *MsgSetRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetRewardsResponse proto.InternalMessageInfo

func (m *MsgSetRewardsResponse) GetPreviousCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.PreviousCoins
	}
	return nil
}

func (m *MsgSetRewardsResponse) GetPreviousLastRewardHeight() int64 {
	if m != nil {
		return m.PreviousLastRewardHeight
	}
	return 0
}

func (m *MsgSetRewardsResponse) GetNewCoins() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.NewCoins
	}
	return nil
}

func (m *MsgSetRewardsResponse) GetNewLastRewardHeight() int64 {
	if m != nil {
		return m.NewLastRewardHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgSetRewards)(nil), "tendermint.spn.reward.MsgSetRewards")
	proto.RegisterType((*MsgSetRewardsResponse)(nil), "tendermint.spn.reward.MsgSetRewardsResponse")
}

func init() { proto.RegisterFile("reward/tx.proto", fileDescriptor_837cc604acddc9f4) }

var fileDescriptor_837cc604acddc9f4 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xbd, 0x6e, 0xd4, 0x40,
	0x10, 0xf6, 0x9e, 0x03, 0x0a, 0x8b, 0x22, 0xd0, 0x42, 0x24, 0xe3, 0xc2, 0x67, 0x45, 0x48, 0x58,
	0x28, 0xec, 0x92, 0xd0, 0x51, 0x26, 0x08, 0x81, 0x94, 0x34, 0xa6, 0x83, 0x06, 0xff, 0x8c, 0x6c,
	0x2b, 0xbe, 0xdd, 0xd5, 0xce, 0xde, 0x39, 0xb4, 0xd4, 0x14, 0x88, 0x9a, 0x27, 0xe0, 0x0d, 0x78,
	0x83, 0x94, 0x29, 0xa9, 0x02, 0xba, 0x7b, 0x0b, 0x2a, 0x64, 0xfb, 0xee, 0x94, 0x83, 0x43, 0x4a,
	0x07, 0x95, 0x67, 0xe6, 0x9b, 0x19, 0x7f, 0xdf, 0xce, 0x0c, 0xbd, 0x65, 0xa0, 0x49, 0x4c, 0x2e,
	0xec, 0x29, 0xd7, 0x46, 0x59, 0xc5, 0xb6, 0x2d, 0xc8, 0x1c, 0xcc, 0xa8, 0x92, 0x96, 0xa3, 0x96,
	0xbc, 0xc7, 0xfd, 0x20, 0x53, 0x38, 0x52, 0x28, 0xd2, 0x04, 0x41, 0x4c, 0xf6, 0x52, 0xb0, 0xc9,
	0x9e, 0xc8, 0x54, 0x25, 0xfb, 0x32, 0xff, 0x6e, 0xa1, 0x0a, 0xd5, 0x99, 0xa2, 0xb5, 0xfa, 0xe8,
	0xce, 0xfb, 0x01, 0xdd, 0x3a, 0xc6, 0xe2, 0x15, 0xd8, 0xb8, 0x6b, 0x83, 0xcc, 0xa7, 0x9b, 0xda,
	0xa8, 0x49, 0x95, 0x83, 0xf1, 0x48, 0x48, 0xa2, 0x1b, 0xf1, 0xd2, 0x6f, 0xb1, 0x3a, 0x19, 0xcb,
	0xac, 0x7c, 0xf9, 0xcc, 0x1b, 0x84, 0x24, 0xda, 0x88, 0x97, 0x3e, 0xfb, 0x40, 0xe8, 0xb5, 0xf6,
	0x77, 0xe8, 0xb9, 0xa1, 0x1b, 0xdd, 0xdc, 0xbf, 0xc7, 0x7b, 0x42, 0xbc, 0x25, 0xc4, 0xe7, 0x84,
	0xf8, 0xa1, 0xaa, 0xe4, 0xc1, 0x9b, 0xb3, 0x8b, 0xa1, 0xf3, 0xf3, 0x62, 0xf8, 0xa0, 0xa8, 0x6c,
	0x39, 0x4e, 0x79, 0xa6, 0x46, 0x62, 0xce, 0xbe, 0xff, 0x3c, 0xc2, 0xfc, 0x44, 0xd8, 0x77, 0x1a,
	0xb0, 0x2b, 0xf8, 0xf2, 0x7d, 0x18, 0x5d, 0x31, 0x15, 0xe3, 0x9e, 0x04, 0x7b, 0x48, 0x6f, 0xd7,
	0x09, 0xce, 0x55, 0xbd, 0x80, 0xaa, 0x28, 0xad, 0xb7, 0x11, 0x92, 0xc8, 0x8d, 0xff, 0x88, 0xef,
	0x7c, 0x75, 0xe9, 0xf6, 0xca, 0x23, 0xc4, 0x80, 0x5a, 0x49, 0x04, 0xf6, 0x99, 0xd0, 0x2d, 0x6d,
	0x60, 0x52, 0xa9, 0x31, 0x76, 0xed, 0x3d, 0xf2, 0x4f, 0xc5, 0xad, 0x92, 0x61, 0x4f, 0xa9, 0xb7,
	0x08, 0x1c, 0xfd, 0x2e, 0x76, 0xd0, 0x89, 0xfd, 0x2b, 0xce, 0x3e, 0x11, 0xba, 0x29, 0xa1, 0x39,
	0xfc, 0x0f, 0x46, 0xb6, 0xe4, 0xc1, 0x1e, 0xd3, 0x3b, 0x12, 0x9a, 0xa3, 0xf5, 0x83, 0x5b, 0x07,
	0xed, 0x17, 0xd4, 0x3d, 0xc6, 0x82, 0xbd, 0xa5, 0xf4, 0xd2, 0x0e, 0xdf, 0xe7, 0x6b, 0x6f, 0x84,
	0xaf, 0x0c, 0xd9, 0xdf, 0xbd, 0x4a, 0xd6, 0x62, 0x15, 0x0e, 0x9e, 0x9f, 0x4d, 0x03, 0x72, 0x3e,
	0x0d, 0xc8, 0x8f, 0x69, 0x40, 0x3e, 0xce, 0x02, 0xe7, 0x7c, 0x16, 0x38, 0xdf, 0x66, 0x81, 0xf3,
	0x7a, 0xf7, 0x92, 0x50, 0xd4, 0x50, 0xd7, 0x58, 0x26, 0x1a, 0x84, 0x04, 0xdb, 0x28, 0x73, 0x22,
	0x4e, 0xc5, 0xe2, 0x82, 0x5b, 0xc9, 0xe9, 0xf5, 0xee, 0xf0, 0x9e, 0xfc, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0xcb, 0x38, 0x49, 0x08, 0xd8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetRewards(ctx context.Context, in *MsgSetRewards, opts ...grpc.CallOption) (*MsgSetRewardsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetRewards(ctx context.Context, in *MsgSetRewards, opts ...grpc.CallOption) (*MsgSetRewardsResponse, error) {
	out := new(MsgSetRewardsResponse)
	err := c.cc.Invoke(ctx, "/tendermint.spn.reward.Msg/SetRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetRewards(context.Context, *MsgSetRewards) (*MsgSetRewardsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetRewards(ctx context.Context, req *MsgSetRewards) (*MsgSetRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRewards not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetRewards)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tendermint.spn.reward.Msg/SetRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetRewards(ctx, req.(*MsgSetRewards))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tendermint.spn.reward.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRewards",
			Handler:    _Msg_SetRewards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reward/tx.proto",
}

func (m *MsgSetRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastRewardHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LastRewardHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.LaunchID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.LaunchID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewLastRewardHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NewLastRewardHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.NewCoins) > 0 {
		for iNdEx := len(m.NewCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NewCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PreviousLastRewardHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PreviousLastRewardHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PreviousCoins) > 0 {
		for iNdEx := len(m.PreviousCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PreviousCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.LaunchID != 0 {
		n += 1 + sovTx(uint64(m.LaunchID))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.LastRewardHeight != 0 {
		n += 1 + sovTx(uint64(m.LastRewardHeight))
	}
	return n
}

func (m *MsgSetRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.PreviousCoins) > 0 {
		for _, e := range m.PreviousCoins {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.PreviousLastRewardHeight != 0 {
		n += 1 + sovTx(uint64(m.PreviousLastRewardHeight))
	}
	if len(m.NewCoins) > 0 {
		for _, e := range m.NewCoins {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.NewLastRewardHeight != 0 {
		n += 1 + sovTx(uint64(m.NewLastRewardHeight))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchID", wireType)
			}
			m.LaunchID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LaunchID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, github_com_cosmos_cosmos_sdk_types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastRewardHeight", wireType)
			}
			m.LastRewardHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastRewardHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousCoins = append(m.PreviousCoins, github_com_cosmos_cosmos_sdk_types.Coin{})
			if err := m.PreviousCoins[len(m.PreviousCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousLastRewardHeight", wireType)
			}
			m.PreviousLastRewardHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousLastRewardHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewCoins = append(m.NewCoins, github_com_cosmos_cosmos_sdk_types.Coin{})
			if err := m.NewCoins[len(m.NewCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewLastRewardHeight", wireType)
			}
			m.NewLastRewardHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewLastRewardHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
