// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: launch/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the launch module's genesis state.
type GenesisState struct {
	// this line is used by starport scaffolding # genesis/proto/state
	Chains            []Chain            `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains"`
	ChainCounter      uint64             `protobuf:"varint,2,opt,name=chainCounter,proto3" json:"chainCounter,omitempty"`
	GenesisAccounts   []GenesisAccount   `protobuf:"bytes,3,rep,name=genesisAccounts,proto3" json:"genesisAccounts"`
	VestingAccounts   []VestingAccount   `protobuf:"bytes,4,rep,name=vestingAccounts,proto3" json:"vestingAccounts"`
	GenesisValidators []GenesisValidator `protobuf:"bytes,5,rep,name=genesisValidators,proto3" json:"genesisValidators"`
	ParamChanges      []ParamChange      `protobuf:"bytes,6,rep,name=paramChanges,proto3" json:"paramChanges"`
	Requests          []Request          `protobuf:"bytes,7,rep,name=requests,proto3" json:"requests"`
	RequestCounters   []RequestCounter   `protobuf:"bytes,8,rep,name=requestCounters,proto3" json:"requestCounters"`
	Params            Params             `protobuf:"bytes,9,opt,name=params,proto3" json:"params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_02cd66d27edc51cd, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetChains() []Chain {
	if m != nil {
		return m.Chains
	}
	return nil
}

func (m *GenesisState) GetChainCounter() uint64 {
	if m != nil {
		return m.ChainCounter
	}
	return 0
}

func (m *GenesisState) GetGenesisAccounts() []GenesisAccount {
	if m != nil {
		return m.GenesisAccounts
	}
	return nil
}

func (m *GenesisState) GetVestingAccounts() []VestingAccount {
	if m != nil {
		return m.VestingAccounts
	}
	return nil
}

func (m *GenesisState) GetGenesisValidators() []GenesisValidator {
	if m != nil {
		return m.GenesisValidators
	}
	return nil
}

func (m *GenesisState) GetParamChanges() []ParamChange {
	if m != nil {
		return m.ParamChanges
	}
	return nil
}

func (m *GenesisState) GetRequests() []Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *GenesisState) GetRequestCounters() []RequestCounter {
	if m != nil {
		return m.RequestCounters
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type RequestCounter struct {
	LaunchID uint64 `protobuf:"varint,1,opt,name=launchID,proto3" json:"launchID,omitempty"`
	Counter  uint64 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (m *RequestCounter) Reset()         { *m = RequestCounter{} }
func (m *RequestCounter) String() string { return proto.CompactTextString(m) }
func (*RequestCounter) ProtoMessage()    {}
func (*RequestCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_02cd66d27edc51cd, []int{1}
}
func (m *RequestCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RequestCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RequestCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RequestCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestCounter.Merge(m, src)
}
func (m *RequestCounter) XXX_Size() int {
	return m.Size()
}
func (m *RequestCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestCounter.DiscardUnknown(m)
}

var xxx_messageInfo_RequestCounter proto.InternalMessageInfo

func (m *RequestCounter) GetLaunchID() uint64 {
	if m != nil {
		return m.LaunchID
	}
	return 0
}

func (m *RequestCounter) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "tendermint.spn.launch.GenesisState")
	proto.RegisterType((*RequestCounter)(nil), "tendermint.spn.launch.RequestCounter")
}

func init() { proto.RegisterFile("launch/genesis.proto", fileDescriptor_02cd66d27edc51cd) }

var fileDescriptor_02cd66d27edc51cd = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xc7, 0x13, 0xba, 0x4d, 0x17, 0x77, 0x05, 0xc2, 0x14, 0xc9, 0x5a, 0x15, 0xb3, 0x8a, 0x84,
	0xd8, 0x03, 0x4a, 0xa4, 0x72, 0x83, 0x0b, 0x74, 0x51, 0x2b, 0x24, 0x0e, 0x28, 0x88, 0x1e, 0xe0,
	0x80, 0xdc, 0xd4, 0x4a, 0x22, 0xb2, 0x76, 0x88, 0x9d, 0x02, 0x6f, 0xc1, 0x0b, 0xf0, 0x3e, 0x7b,
	0xdc, 0x23, 0x27, 0x84, 0x76, 0x5f, 0x04, 0xc5, 0x9e, 0x04, 0x25, 0xb0, 0xb9, 0xd9, 0x33, 0xff,
	0xf9, 0xcd, 0x87, 0xc7, 0xe8, 0x28, 0x67, 0x95, 0x88, 0xd3, 0x30, 0xe1, 0x82, 0xab, 0x4c, 0x05,
	0x45, 0x29, 0xb5, 0xc4, 0xf7, 0x34, 0x17, 0x57, 0xbc, 0x5c, 0x66, 0x42, 0x07, 0xaa, 0x10, 0x81,
	0x15, 0x4d, 0x8f, 0x12, 0x99, 0x48, 0xa3, 0x08, 0xeb, 0x93, 0x15, 0x4f, 0x1b, 0x44, 0xc9, 0x3f,
	0x57, 0x5c, 0x69, 0xb0, 0x1e, 0x83, 0xf5, 0x9a, 0x2b, 0x9d, 0x89, 0xe4, 0x23, 0x8b, 0x63, 0x59,
	0x89, 0xbe, 0x17, 0xd2, 0xf6, 0xbc, 0xb4, 0xe7, 0xbd, 0x66, 0x79, 0x76, 0xc5, 0xb4, 0x2c, 0xc1,
	0x8f, 0xc1, 0x1f, 0xa7, 0x2c, 0x13, 0x60, 0xbb, 0x0b, 0xb6, 0x82, 0x95, 0x6c, 0x09, 0x7d, 0xf8,
	0x3f, 0xf6, 0xd1, 0xe4, 0xdc, 0x42, 0xde, 0x6a, 0xa6, 0x39, 0x7e, 0x8a, 0x3c, 0x13, 0xa4, 0x88,
	0x3b, 0xdb, 0x9b, 0x1f, 0x9e, 0x1c, 0x07, 0xff, 0xed, 0x34, 0x58, 0xd4, 0xa2, 0xd3, 0xd1, 0xea,
	0xd7, 0x03, 0x27, 0x82, 0x08, 0xec, 0xa3, 0x89, 0x39, 0x2d, 0xea, 0x4a, 0x79, 0x49, 0x6e, 0xcc,
	0xdc, 0xf9, 0x28, 0xea, 0xd8, 0xf0, 0x3b, 0x74, 0x1b, 0x8a, 0x7e, 0x61, 0x3b, 0x52, 0x64, 0xcf,
	0x24, 0x7a, 0xb8, 0x23, 0xd1, 0x79, 0x47, 0x0d, 0x19, 0xfb, 0x8c, 0x1a, 0x0b, 0x73, 0x6c, 0xb1,
	0xa3, 0x41, 0xec, 0x45, 0x47, 0xdd, 0x60, 0x7b, 0x0c, 0xfc, 0x01, 0xdd, 0x81, 0x4c, 0x17, 0xcd,
	0x84, 0x15, 0xd9, 0x37, 0xe0, 0x47, 0xc3, 0xf5, 0xb6, 0x7a, 0x40, 0xff, 0xcb, 0xc1, 0xaf, 0xd1,
	0xc4, 0xbc, 0xc5, 0x22, 0x65, 0x22, 0xe1, 0x8a, 0x78, 0x86, 0xeb, 0xef, 0xe0, 0xbe, 0xf9, 0x2b,
	0x05, 0x64, 0x27, 0x1a, 0x3f, 0x47, 0x63, 0xd8, 0x2f, 0x45, 0x0e, 0x0c, 0x89, 0xee, 0x20, 0x45,
	0x56, 0x06, 0x94, 0x36, 0xaa, 0x9e, 0x21, 0x9c, 0xe1, 0xb1, 0x14, 0x19, 0x0f, 0xce, 0x30, 0xea,
	0xa8, 0x9b, 0x19, 0xf6, 0x18, 0xf8, 0x19, 0xf2, 0xec, 0xca, 0x91, 0x9b, 0x33, 0x77, 0x7e, 0x78,
	0x72, 0x7f, 0xa8, 0x41, 0xd5, 0xac, 0x94, 0x0d, 0xf1, 0xcf, 0xd0, 0xad, 0x6e, 0x16, 0x3c, 0x45,
	0x63, 0x1b, 0xf0, 0xea, 0x25, 0x71, 0xcd, 0x82, 0xb5, 0x77, 0x4c, 0xd0, 0x41, 0xdc, 0xd9, 0xbd,
	0xe6, 0x7a, 0x7a, 0xb6, 0xda, 0x50, 0x77, 0xbd, 0xa1, 0xee, 0xef, 0x0d, 0x75, 0xbf, 0x6f, 0xa9,
	0xb3, 0xde, 0x52, 0xe7, 0xe7, 0x96, 0x3a, 0xef, 0x1f, 0x27, 0x99, 0x4e, 0xab, 0xcb, 0x20, 0x96,
	0xcb, 0x50, 0x15, 0x3c, 0xcf, 0x55, 0xca, 0x0a, 0x1e, 0x0a, 0xae, 0xbf, 0xc8, 0xf2, 0x53, 0xf8,
	0x35, 0x84, 0x6f, 0xa3, 0xbf, 0x15, 0x5c, 0x5d, 0x7a, 0xe6, 0xdb, 0x3c, 0xf9, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x9c, 0xe0, 0x3b, 0xa8, 0x16, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.RequestCounters) > 0 {
		for iNdEx := len(m.RequestCounters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RequestCounters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Requests) > 0 {
		for iNdEx := len(m.Requests) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Requests[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.ParamChanges) > 0 {
		for iNdEx := len(m.ParamChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ParamChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.GenesisValidators) > 0 {
		for iNdEx := len(m.GenesisValidators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GenesisValidators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.VestingAccounts) > 0 {
		for iNdEx := len(m.VestingAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VestingAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.GenesisAccounts) > 0 {
		for iNdEx := len(m.GenesisAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GenesisAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ChainCounter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ChainCounter))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Chains) > 0 {
		for iNdEx := len(m.Chains) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Chains[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RequestCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RequestCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RequestCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Counter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Counter))
		i--
		dAtA[i] = 0x10
	}
	if m.LaunchID != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LaunchID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Chains) > 0 {
		for _, e := range m.Chains {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ChainCounter != 0 {
		n += 1 + sovGenesis(uint64(m.ChainCounter))
	}
	if len(m.GenesisAccounts) > 0 {
		for _, e := range m.GenesisAccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.VestingAccounts) > 0 {
		for _, e := range m.VestingAccounts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GenesisValidators) > 0 {
		for _, e := range m.GenesisValidators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ParamChanges) > 0 {
		for _, e := range m.ParamChanges {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Requests) > 0 {
		for _, e := range m.Requests {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RequestCounters) > 0 {
		for _, e := range m.RequestCounters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *RequestCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaunchID != 0 {
		n += 1 + sovGenesis(uint64(m.LaunchID))
	}
	if m.Counter != 0 {
		n += 1 + sovGenesis(uint64(m.Counter))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chains = append(m.Chains, Chain{})
			if err := m.Chains[len(m.Chains)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainCounter", wireType)
			}
			m.ChainCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisAccounts = append(m.GenesisAccounts, GenesisAccount{})
			if err := m.GenesisAccounts[len(m.GenesisAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VestingAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VestingAccounts = append(m.VestingAccounts, VestingAccount{})
			if err := m.VestingAccounts[len(m.VestingAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisValidators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisValidators = append(m.GenesisValidators, GenesisValidator{})
			if err := m.GenesisValidators[len(m.GenesisValidators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParamChanges = append(m.ParamChanges, ParamChange{})
			if err := m.ParamChanges[len(m.ParamChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requests", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requests = append(m.Requests, Request{})
			if err := m.Requests[len(m.Requests)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestCounters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestCounters = append(m.RequestCounters, RequestCounter{})
			if err := m.RequestCounters[len(m.RequestCounters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RequestCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RequestCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RequestCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchID", wireType)
			}
			m.LaunchID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LaunchID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			m.Counter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Counter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
