// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: monitoringp/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the monitoringp module's genesis state.
type GenesisState struct {
	PortId              string               `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ConsumerClientID    *ConsumerClientID    `protobuf:"bytes,2,opt,name=consumerClientID,proto3" json:"consumerClientID,omitempty"`
	ConnectionChannelID *ConnectionChannelID `protobuf:"bytes,3,opt,name=connectionChannelID,proto3" json:"connectionChannelID,omitempty"`
	MonitoringInfo      *MonitoringInfo      `protobuf:"bytes,4,opt,name=monitoringInfo,proto3" json:"monitoringInfo,omitempty"`
	Params              Params               `protobuf:"bytes,5,opt,name=params,proto3" json:"params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_daeb174358fef22d, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *GenesisState) GetConsumerClientID() *ConsumerClientID {
	if m != nil {
		return m.ConsumerClientID
	}
	return nil
}

func (m *GenesisState) GetConnectionChannelID() *ConnectionChannelID {
	if m != nil {
		return m.ConnectionChannelID
	}
	return nil
}

func (m *GenesisState) GetMonitoringInfo() *MonitoringInfo {
	if m != nil {
		return m.MonitoringInfo
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "tendermint.spn.monitoringp.GenesisState")
}

func init() { proto.RegisterFile("monitoringp/genesis.proto", fileDescriptor_daeb174358fef22d) }

var fileDescriptor_daeb174358fef22d = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xd1, 0x4a, 0xf3, 0x30,
	0x14, 0xc7, 0xdb, 0x7d, 0xfb, 0x26, 0x56, 0x11, 0xa9, 0x82, 0xb5, 0x17, 0x75, 0x0e, 0xc1, 0x21,
	0xd2, 0xa0, 0xbe, 0x80, 0x6c, 0x03, 0x29, 0x22, 0x48, 0xbd, 0x11, 0x6f, 0x4a, 0xd7, 0x65, 0x5d,
	0xb0, 0x3d, 0x09, 0x49, 0x86, 0xfa, 0x16, 0x3e, 0xd6, 0x2e, 0x77, 0xe9, 0x95, 0xc8, 0xf6, 0x16,
	0x5e, 0xc9, 0xd2, 0x4a, 0x6b, 0xd5, 0x79, 0x77, 0x42, 0x7e, 0xff, 0x5f, 0xce, 0xc9, 0x31, 0x76,
	0x53, 0x0a, 0x44, 0x52, 0x4e, 0x20, 0x66, 0x28, 0xc6, 0x80, 0x05, 0x11, 0x2e, 0xe3, 0x54, 0x52,
	0xd3, 0x96, 0x18, 0x06, 0x98, 0xa7, 0x04, 0xa4, 0x2b, 0x18, 0xb8, 0x25, 0xd2, 0xde, 0x8e, 0x69,
	0x4c, 0x15, 0x86, 0x16, 0x55, 0x96, 0xb0, 0xad, 0xb2, 0x8c, 0x85, 0x3c, 0x4c, 0x73, 0x97, 0x7d,
	0x50, 0xbe, 0x89, 0x28, 0x88, 0x71, 0x8a, 0x79, 0x10, 0x25, 0x04, 0x83, 0x0c, 0xc8, 0x20, 0xa7,
	0x0e, 0x2b, 0x14, 0xe0, 0x48, 0x12, 0x0a, 0x41, 0x34, 0x0a, 0x01, 0x70, 0x52, 0x80, 0xfb, 0x65,
	0xb0, 0xa8, 0x03, 0x02, 0xc3, 0xbc, 0x97, 0xd6, 0x7b, 0xcd, 0x58, 0xbf, 0xc8, 0xe6, 0xb9, 0x91,
	0xa1, 0xc4, 0xe6, 0x8e, 0xb1, 0xc2, 0x28, 0x5f, 0xbc, 0x66, 0xe9, 0x4d, 0xbd, 0xbd, 0xea, 0x37,
	0x16, 0x47, 0x6f, 0x60, 0xde, 0x1a, 0x9b, 0x9f, 0x1d, 0x75, 0x55, 0x43, 0x5e, 0xcf, 0xaa, 0x35,
	0xf5, 0xf6, 0xda, 0xe9, 0xb1, 0xfb, 0xfb, 0x17, 0xb8, 0xdd, 0x4a, 0xc6, 0xff, 0x66, 0x31, 0x43,
	0x63, 0xab, 0x98, 0xa2, 0x9b, 0x0d, 0xe1, 0xf5, 0xac, 0x7f, 0x4a, 0x8e, 0xfe, 0x90, 0x57, 0x63,
	0xfe, 0x4f, 0x2e, 0xd3, 0x37, 0x36, 0x8a, 0x9c, 0x07, 0x43, 0x6a, 0xd5, 0x95, 0xfd, 0x68, 0x99,
	0xfd, 0xea, 0x4b, 0xc2, 0xaf, 0x18, 0xcc, 0x73, 0xa3, 0x91, 0x2d, 0xcf, 0xfa, 0xaf, 0x5c, 0xad,
	0x65, 0xae, 0x6b, 0x45, 0x76, 0xea, 0x93, 0xd7, 0x3d, 0xcd, 0xcf, 0x73, 0x9d, 0xcb, 0xc9, 0xcc,
	0xd1, 0xa7, 0x33, 0x47, 0x7f, 0x9b, 0x39, 0xfa, 0xf3, 0xdc, 0xd1, 0xa6, 0x73, 0x47, 0x7b, 0x99,
	0x3b, 0xda, 0xdd, 0x49, 0x4c, 0xe4, 0x68, 0xdc, 0x77, 0x23, 0x9a, 0x22, 0xc1, 0x70, 0x92, 0x88,
	0x51, 0xc8, 0x30, 0x02, 0x2c, 0x1f, 0x28, 0xbf, 0x47, 0x8f, 0xa8, 0xbc, 0x59, 0xf9, 0xc4, 0xb0,
	0xe8, 0x37, 0xd4, 0x42, 0xcf, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x24, 0xb7, 0x3f, 0xab,
	0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.MonitoringInfo != nil {
		{
			size, err := m.MonitoringInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.ConnectionChannelID != nil {
		{
			size, err := m.ConnectionChannelID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ConsumerClientID != nil {
		{
			size, err := m.ConsumerClientID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.ConsumerClientID != nil {
		l = m.ConsumerClientID.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.ConnectionChannelID != nil {
		l = m.ConnectionChannelID.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.MonitoringInfo != nil {
		l = m.MonitoringInfo.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerClientID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsumerClientID == nil {
				m.ConsumerClientID = &ConsumerClientID{}
			}
			if err := m.ConsumerClientID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionChannelID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConnectionChannelID == nil {
				m.ConnectionChannelID = &ConnectionChannelID{}
			}
			if err := m.ConnectionChannelID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonitoringInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MonitoringInfo == nil {
				m.MonitoringInfo = &MonitoringInfo{}
			}
			if err := m.MonitoringInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
