// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: monitoringp/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/spellshape/network/pkg/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	LastBlockHeight         int64                `protobuf:"varint,1,opt,name=lastBlockHeight,proto3" json:"lastBlockHeight,omitempty"`
	ConsumerChainID         string               `protobuf:"bytes,2,opt,name=consumerChainID,proto3" json:"consumerChainID,omitempty"`
	ConsumerConsensusState  types.ConsensusState `protobuf:"bytes,3,opt,name=consumerConsensusState,proto3" json:"consumerConsensusState"`
	ConsumerUnbondingPeriod int64                `protobuf:"varint,4,opt,name=consumerUnbondingPeriod,proto3" json:"consumerUnbondingPeriod,omitempty"`
	ConsumerRevisionHeight  uint64               `protobuf:"varint,5,opt,name=consumerRevisionHeight,proto3" json:"consumerRevisionHeight,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_14b90118a5ef3574, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLastBlockHeight() int64 {
	if m != nil {
		return m.LastBlockHeight
	}
	return 0
}

func (m *Params) GetConsumerChainID() string {
	if m != nil {
		return m.ConsumerChainID
	}
	return ""
}

func (m *Params) GetConsumerConsensusState() types.ConsensusState {
	if m != nil {
		return m.ConsumerConsensusState
	}
	return types.ConsensusState{}
}

func (m *Params) GetConsumerUnbondingPeriod() int64 {
	if m != nil {
		return m.ConsumerUnbondingPeriod
	}
	return 0
}

func (m *Params) GetConsumerRevisionHeight() uint64 {
	if m != nil {
		return m.ConsumerRevisionHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "tendermint.spn.monitoringp.Params")
}

func init() { proto.RegisterFile("monitoringp/params.proto", fileDescriptor_14b90118a5ef3574) }

var fileDescriptor_14b90118a5ef3574 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x33, 0x6d, 0xfe, 0x85, 0x7f, 0x5c, 0x14, 0x82, 0x68, 0xe8, 0x22, 0x0d, 0xe2, 0x22,
	0xab, 0x0c, 0x2a, 0x88, 0xb8, 0xac, 0x2e, 0x14, 0x37, 0x25, 0xe2, 0xc6, 0x5d, 0x92, 0x5e, 0x92,
	0xa1, 0xc9, 0xbd, 0xc3, 0xcc, 0xd4, 0x8f, 0xb7, 0x70, 0xe9, 0xd2, 0xc7, 0xf0, 0x11, 0xba, 0xec,
	0xd2, 0x95, 0x48, 0xfb, 0x22, 0xd2, 0xd4, 0x8f, 0x5a, 0xc8, 0x6e, 0x38, 0xe7, 0x37, 0x97, 0x73,
	0x38, 0x8e, 0x57, 0x11, 0x0a, 0x43, 0x4a, 0x60, 0x2e, 0xb9, 0x4c, 0x54, 0x52, 0xe9, 0x48, 0x2a,
	0x32, 0xe4, 0xf6, 0x0c, 0xe0, 0x08, 0x54, 0x25, 0xd0, 0x44, 0x5a, 0x62, 0xb4, 0x06, 0xf6, 0xb6,
	0x73, 0xca, 0xa9, 0xc6, 0xf8, 0xf2, 0xb5, 0xfa, 0xd1, 0xeb, 0x9a, 0x47, 0x09, 0x9a, 0x8b, 0x34,
	0x5b, 0x09, 0x7b, 0xaf, 0x2d, 0xa7, 0x33, 0xac, 0x6f, 0xba, 0xa1, 0xd3, 0x2d, 0x13, 0x6d, 0x06,
	0x25, 0x65, 0xe3, 0x0b, 0x10, 0x79, 0x61, 0x3c, 0x16, 0xb0, 0xb0, 0x1d, 0x6f, 0xca, 0x4b, 0x32,
	0x23, 0xd4, 0x93, 0x0a, 0xd4, 0x59, 0x91, 0x08, 0xbc, 0x3c, 0xf7, 0x5a, 0x01, 0x0b, 0xff, 0xc7,
	0x9b, 0xb2, 0x9b, 0x3a, 0x3b, 0x3f, 0x12, 0xa1, 0x06, 0xd4, 0x13, 0x7d, 0x6d, 0x12, 0x03, 0x5e,
	0x3b, 0x60, 0xe1, 0xd6, 0xe1, 0x7e, 0xb4, 0x51, 0xa1, 0xce, 0x17, 0xfd, 0x65, 0x07, 0xf6, 0xf4,
	0xbd, 0x6f, 0xc5, 0x0d, 0x97, 0xdc, 0x13, 0x67, 0xf7, 0xdb, 0xb9, 0xc1, 0x94, 0x70, 0x24, 0x30,
	0x1f, 0x82, 0x12, 0x34, 0xf2, 0xec, 0x3a, 0x7f, 0x93, 0xed, 0x1e, 0xff, 0xa6, 0x8b, 0xe1, 0x4e,
	0x68, 0x41, 0xf8, 0x55, 0xfc, 0x5f, 0xc0, 0x42, 0x3b, 0x6e, 0x70, 0x4f, 0xed, 0xe7, 0x97, 0xbe,
	0x35, 0xb8, 0x9a, 0xce, 0x7d, 0x36, 0x9b, 0xfb, 0xec, 0x63, 0xee, 0xb3, 0xa7, 0x85, 0x6f, 0xcd,
	0x16, 0xbe, 0xf5, 0xb6, 0xf0, 0xad, 0xdb, 0x83, 0x5c, 0x98, 0x62, 0x92, 0x46, 0x19, 0x55, 0x5c,
	0x4b, 0x28, 0x4b, 0x5d, 0x24, 0x12, 0x38, 0x82, 0xb9, 0x27, 0x35, 0xe6, 0x0f, 0x7c, 0x7d, 0xd1,
	0xba, 0x71, 0xda, 0xa9, 0xe7, 0x38, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x97, 0x81, 0x20, 0xf5,
	0xed, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsumerRevisionHeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ConsumerRevisionHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.ConsumerUnbondingPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ConsumerUnbondingPeriod))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.ConsumerConsensusState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ConsumerChainID) > 0 {
		i -= len(m.ConsumerChainID)
		copy(dAtA[i:], m.ConsumerChainID)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ConsumerChainID)))
		i--
		dAtA[i] = 0x12
	}
	if m.LastBlockHeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.LastBlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LastBlockHeight != 0 {
		n += 1 + sovParams(uint64(m.LastBlockHeight))
	}
	l = len(m.ConsumerChainID)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.ConsumerConsensusState.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.ConsumerUnbondingPeriod != 0 {
		n += 1 + sovParams(uint64(m.ConsumerUnbondingPeriod))
	}
	if m.ConsumerRevisionHeight != 0 {
		n += 1 + sovParams(uint64(m.ConsumerRevisionHeight))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastBlockHeight", wireType)
			}
			m.LastBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerConsensusState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConsumerConsensusState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerUnbondingPeriod", wireType)
			}
			m.ConsumerUnbondingPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsumerUnbondingPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerRevisionHeight", wireType)
			}
			m.ConsumerRevisionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsumerRevisionHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
